# Generated by Django 4.0 on 2022-07-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileId', models.IntegerField()),
                ('mobileNo', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('isMobileNoVerify', models.BooleanField(default=False)),
                ('isEmailVerify', models.BooleanField(default=False)),
            ],
        ),
    ]
