# Generated by Django 4.0 on 2022-07-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_profile_email_alter_profile_mobileno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
