# Generated by Django 4.0 on 2022-07-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='counter',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
