# Generated by Django 4.0 on 2022-07-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='education',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='employee',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='martialStatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='noOfDependents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='panNumber',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='propertyArea',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
