# Generated by Django 4.0 on 2022-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_profileid_personaldetails_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eligibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isKycVerify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isPersonalDetailsVerify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='loanRequest',
            field=models.BooleanField(default=False),
        ),
    ]
