# Generated by Django 4.0 on 2022-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_eligibility_profile_iskycverify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loanRequest',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='dob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='existingEmi',
            field=models.IntegerField(default=0),
        ),
    ]
