# Generated by Django 4.0 on 2022-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_loanrequest_personaldetails_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='aadtharFront',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='aatharBack',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
