# Generated by Django 4.0 on 2022-07-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_personaldetails_aadtharfront_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='aadtharFront',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='aatharBack',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
