# Generated by Django 4.0 on 2022-07-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_personaldetails_aadtharfront_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='aadtharFront',
            new_name='aadharBack',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='aatharBack',
            new_name='aadharFront',
        ),
    ]
