# Generated by Django 4.0 on 2022-07-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bankdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='eligibility',
            new_name='eligibile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isEmailVerify',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isMobileNoVerify',
        ),
    ]
